# Generated by Django 4.2.3 on 2023-08-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_songvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
